Load the dataset into a DataFrame df_ipl and display first 5 rows.

In [2]:
import pandas as pd
df = pd.read_csv(r"F:\Data_Analytics\Python\IPL2025Batters.csv")
df.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

Display shape and column names of the dataset.

In [6]:
print(df.shape)
print(df.columns)

(156, 14)
Index(['Player Name', 'Team', 'Runs', 'Matches', 'Inn', 'No', 'HS', 'AVG',
       'BF', 'SR', '100s', '50s', '4s', '6s'],
      dtype='object')

Display only "Player Name" and "Runs" columns.

In [13]:
df[['Player Name', 'Runs']]

           Player Name  Runs
0        Sai Sudharsan   759
1    Surya Kumar Yadav   717
2          Virat Kohli   657
3         Shubman Gill   650
4       Mitchell Marsh   627
..                 ...   ...
151      Khaleel Ahmed     1
152       Mohit Sharma     1
153   Donovan Ferreira     1
154      Digvesh Singh     1
155     Manoj Bhandage     1

[156 rows x 2 columns]

Display data types using info().

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

Select players who scored more than 500 runs.

In [16]:
df.loc[df["Runs"]>500, ["Player Name", "Runs"]]

          Player Name  Runs
0       Sai Sudharsan   759
1   Surya Kumar Yadav   717
2         Virat Kohli   657
3        Shubman Gill   650
4      Mitchell Marsh   627
5        Shreyas Iyer   604
6    Yashasvi Jaiswal   559
7   Prabhsimran Singh   549
8           K L Rahul   539
9         Jos Buttler   538
10    Nicholas Pooran   524

Select "Player Name" and "SR" where SR > 150 using loc.

In [17]:
df.loc[df["SR"]>150, ["Player Name", "SR"]]

             Player Name      SR
0          Sai Sudharsan  156.17
1      Surya Kumar Yadav  167.91
3           Shubman Gill  155.87
4         Mitchell Marsh  163.70
5           Shreyas Iyer  175.07
6       Yashasvi Jaiswal  159.71
7      Prabhsimran Singh  160.52
9            Jos Buttler  163.03
10       Nicholas Pooran  196.25
11      Heinrich Klaasen  172.69
12         Priyansh Arya  179.24
14       Abhishek Sharma  193.39
16             Phil Salt  175.98
17           Riyan Parag  166.52
19        Ryan Rickelton  150.97
20           Travis Head  162.60
23          Ishan Kishan  152.58
24        Shashank Singh  153.50
26           Dhruv Jurel  156.33
31        Tristan Stubbs  150.75
33   Sherfane Rutherford  157.29
35           Josh Inglis  162.57
37            Axar Patel  157.48
38         Jitesh Sharma  176.35
39   Vaibhav Suryavanshi  206.55
40            Naman Dhir  182.60
41      Devdutt Padikkal  150.60
42          Sunil Narine  170.83
43          Ayush Mhatre  188.97
45          Aniket Verma  166.19
47         Dewald Brevis  180.00
48         Hardik Pandya  163.50
49           Nitish Rana  161.94
50           Rinku Singh  153.73
51       Ashutosh Sharma  160.62
53            Karun Nair  172.17
56             Tim David  185.14
58         Shahrukh Khan  179.00
59         Andre Russell  163.72
60           Abdul Samad  176.34
61        Marcus Stoinis  186.04
65          Vipraj Nigam  179.74
67     Washington Sundar  166.25
68       Ruturaj Gaikwad  150.61
69          Sameer Rizvi  153.16
74         Shubham Dubey  160.60
75         Rahul Tewatia  167.79
76           Pat Cummins  167.24
80        Jonny Bairstow  184.78
84      Romario Shepherd  291.66
85           Urvil Patel  212.50
86         Jacob Bethell  171.79
103           Avesh Khan  175.00
105         Kusal Mendis  200.00
108       Gerald Coetzee  154.54
109        Jamie Overton  214.28
124        Kwena Maphaka  400.00
125       Raj Angad Bawa  200.00
129           Akash Deep  300.00
137      Lockie Ferguson  400.00

Select players from team "RCB".

In [19]:
df.loc[df["Team"] == "RCB", ["Player Name", "Team"]]

           Player Name Team
2          Virat Kohli  RCB
16           Phil Salt  RCB
28       Rajat Patidar  RCB
38       Jitesh Sharma  RCB
41    Devdutt Padikkal  RCB
56           Tim David  RCB
72    Liam Livingstone  RCB
73       Krunal Pandya  RCB
77      Mayank Agarwal  RCB
84    Romario Shepherd  RCB
86       Jacob Bethell  RCB
112  Bhuvneshwar Kumar  RCB
138         Yash Dayal  RCB
155     Manoj Bhandage  RCB

Select players where Runs > 600 and display only "Player Name" and "Team".

In [21]:
df.loc[df["Runs"] > 600, ["Player Name", "Team"]]

         Player Name  Team
0      Sai Sudharsan    GT
1  Surya Kumar Yadav    MI
2        Virat Kohli   RCB
3       Shubman Gill    GT
4     Mitchell Marsh   LSG
5       Shreyas Iyer  PBKS

Select players where 50s >= 5.

In [22]:
df.loc[df["50s"] > 5, ["Player Name"]]

        Player Name
0     Sai Sudharsan
2       Virat Kohli
3      Shubman Gill
4    Mitchell Marsh
5      Shreyas Iyer
6  Yashasvi Jaiswal

Select players with at least one century (100s > 0).

In [23]:
df.loc[df["100s"] > 0, ["Player Name"]]

            Player Name
0         Sai Sudharsan
4        Mitchell Marsh
8             K L Rahul
11     Heinrich Klaasen
12        Priyansh Arya
14      Abhishek Sharma
23         Ishan Kishan
36         Rishabh Pant
39  Vaibhav Suryavanshi

Select players where Runs > 500 AND SR > 140.

In [28]:
df.loc[(df["Runs"] > 500) & (df["SR"] > 140), ["Player Name"]]

          Player Name
0       Sai Sudharsan
1   Surya Kumar Yadav
2         Virat Kohli
3        Shubman Gill
4      Mitchell Marsh
5        Shreyas Iyer
6    Yashasvi Jaiswal
7   Prabhsimran Singh
8           K L Rahul
9         Jos Buttler
10    Nicholas Pooran

Select players where Team = "MI" AND Runs > 400.

In [29]:
df.loc[(df["Team"] == "MI") & (df["Runs"] > 400), ["Player Name"]]

          Player Name
1   Surya Kumar Yadav
15       Rohit Sharma

Sort players by Runs in descending order.

In [12]:
df.sort_values(by = 'Runs', ascending=False)[['Player Name', 'Runs']]

           Player Name  Runs
0        Sai Sudharsan   759
1    Surya Kumar Yadav   717
2          Virat Kohli   657
3         Shubman Gill   650
4       Mitchell Marsh   627
..                 ...   ...
151      Khaleel Ahmed     1
152       Mohit Sharma     1
153   Donovan Ferreira     1
154      Digvesh Singh     1
155     Manoj Bhandage     1

[156 rows x 2 columns]

In [10]:
df[['Player Name', 'Runs']].sort_values(by='Runs', ascending=False)       # [[]] used for multiple columns

           Player Name  Runs
0        Sai Sudharsan   759
1    Surya Kumar Yadav   717
2          Virat Kohli   657
3         Shubman Gill   650
4       Mitchell Marsh   627
..                 ...   ...
151      Khaleel Ahmed     1
152       Mohit Sharma     1
153   Donovan Ferreira     1
154      Digvesh Singh     1
155     Manoj Bhandage     1

[156 rows x 2 columns]

Difference between df["Runs"] and df[["Runs"]]

In [30]:
df["Runs"]              # Series format return

0      759
1      717
2      657
3      650
4      627
      ...
151      1
152      1
153      1
154      1
155      1
Name: Runs, Length: 156, dtype: int64

In [32]:
df[["Runs"]]         # DataFrame format

     Runs
0     759
1     717
2     657
3     650
4     627
..    ...
151     1
152     1
153     1
154     1
155     1

[156 rows x 1 columns]

**Why use `&` instead of 'and'?**

1. & operator works for each row (Element-wise comparison).
2. python works on c++ in backend and c++ supports & operator.
3. 'and' for single boolean values

and - "Is this ONE thing true?"
& - "Check ALL rows one by one"