In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

Create a pandas series

In [4]:
a = pd.Series([10,20,30,40,50])
a

0    10
1    20
2    30
3    40
4    50
dtype: int64

Create Series with custom index

In [9]:
b = pd.Series([10,20,30,40,50], index = ("a", "b", "c", "d", "e"))
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

Create Series from dictionary

In [11]:
data = {"a":10, "b" : 20, "c" : 30, "d" :40, "e" : 50}
c = pd.Series(data)
c

a    10
b    20
c    30
d    40
e    50
dtype: int64

Make dataframe from dictionary

In [14]:
data = {
"Math" : [85,96,83,82],
"Science" : [90,92,93,84]
}
df = pd.DataFrame(data)
df

   Math  Science
0    85       90
1    96       92
2    83       93
3    82       84

DataFrame with custom index

In [15]:
df1 = pd.DataFrame(data, index=["a", "b", "c", "d" ])
df1

   Math  Science
a    85       90
b    96       92
c    83       93
d    82       84

DataFrame from Series

In [16]:
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

df = pd.DataFrame({'col1': s1, 'col2': s2})
df

   col1  col2
0     1     4
1     2     5
2     3     6

In [18]:
df2 = pd.DataFrame({
    'ShipmentID': [1001, 1002, 1003, 1004, 1005],
    'Origin': ['NY', 'SF', 'Dallas', 'Chicago', 'Miami'],
    'Destination': ['Boston', 'Seattle', 'Houston', 'Atlanta', 'Denver'],
    'Weight_kg': [12.5, 8.0, 15.0, 7.5, 10.0],
    'Fragile': [True, False, True, False, True],
    'Status': ['Delivered', 'In Transit', 'Delayed', 'Delivered', 'Delayed']
})

In [20]:
df2

   ShipmentID   Origin Destination  Weight_kg  Fragile      Status
0        1001       NY      Boston       12.5     True   Delivered
1        1002       SF     Seattle        8.0    False  In Transit
2        1003   Dallas     Houston       15.0     True     Delayed
3        1004  Chicago     Atlanta        7.5    False   Delivered
4        1005    Miami      Denver       10.0     True     Delayed

In [21]:
df2.shape

(5, 6)

In [23]:
df2.dtypes

ShipmentID       int64
Origin          object
Destination     object
Weight_kg      float64
Fragile           bool
Status          object
dtype: object

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ShipmentID   5 non-null      int64
 1   Origin       5 non-null      object
 2   Destination  5 non-null      object
 3   Weight_kg    5 non-null      float64
 4   Fragile      5 non-null      bool
 5   Status       5 non-null      object
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 337.0+ bytes

In [28]:
df2["Status"]

0     Delivered
1    In Transit
2       Delayed
3     Delivered
4       Delayed
Name: Status, dtype: object

In [31]:
df2["Status"].value_counts()

Status
Delivered     2
Delayed       2
In Transit    1
Name: count, dtype: int64

In [34]:
df2.columns

Index(['ShipmentID', 'Origin', 'Destination', 'Weight_kg', 'Fragile',
       'Status'],
      dtype='object')

In [35]:
data = {
    'A': [101,102,103],
    'B':[201,202,203],
    'C': [301,302,303]
    }
s1 = pd.DataFrame(data, index=['a','b','c'])
s1

     A    B    C
a  101  201  301
b  102  202  302
c  103  203  303

Select column

In [36]:
s1['B']

a    201
b    202
c    203
Name: B, dtype: int64

Multiple columns

In [37]:
s1[['B', 'C']]

     B    C
a  201  301
b  202  302
c  203  303

loc (label-based)

In [39]:
s1.loc['a']

A    101
B    201
C    301
Name: a, dtype: int64

In [43]:
s1.loc['c']

A    103
B    203
C    303
Name: c, dtype: int64

In [42]:
print(s1.loc['b', 'B'])

202

In [44]:
print(s1.loc['c', 'B'])

203

iloc (index-based)

In [45]:
print(s1.iloc[0])

A    101
B    201
C    301
Name: a, dtype: int64

In [46]:
print(s1.iloc[1])

A    102
B    202
C    302
Name: b, dtype: int64

In [47]:
print(s1.iloc[1,1])

202

In [48]:
print(s1.iloc[2,2])

303

In [49]:
print(s1.iloc[2,0])

103

How will you filter rows where Weight > 10 using loc?

In [51]:
df2

   ShipmentID   Origin Destination  Weight_kg  Fragile      Status
0        1001       NY      Boston       12.5     True   Delivered
1        1002       SF     Seattle        8.0    False  In Transit
2        1003   Dallas     Houston       15.0     True     Delayed
3        1004  Chicago     Atlanta        7.5    False   Delivered
4        1005    Miami      Denver       10.0     True     Delayed

In [53]:
df2['Weight_kg'] > 10

0     True
1    False
2     True
3    False
4    False
Name: Weight_kg, dtype: bool

In [54]:
df2[df2['Weight_kg'] > 10]           #Shows rows

   ShipmentID  Origin Destination  Weight_kg  Fragile     Status
0        1001      NY      Boston       12.5     True  Delivered
2        1003  Dallas     Houston       15.0     True    Delayed

In [56]:
df2.loc[df2['Weight_kg']>10]

   ShipmentID  Origin Destination  Weight_kg  Fragile     Status
0        1001      NY      Boston       12.5     True  Delivered
2        1003  Dallas     Houston       15.0     True    Delayed

How will you select only 'Destination' column?

In [57]:
df2['Destination']

0     Boston
1    Seattle
2    Houston
3    Atlanta
4     Denver
Name: Destination, dtype: object

Cost = Weight * 10?

In [60]:
df2['Cost'] = df2['Weight_kg']*10
df2

   ShipmentID   Origin Destination  Weight_kg  Fragile      Status   Cost
0        1001       NY      Boston       12.5     True   Delivered  125.0
1        1002       SF     Seattle        8.0    False  In Transit   80.0
2        1003   Dallas     Houston       15.0     True     Delayed  150.0
3        1004  Chicago     Atlanta        7.5    False   Delivered   75.0
4        1005    Miami      Denver       10.0     True     Delayed  100.0

In [61]:
df

   col1  col2
0     1     4
1     2     5
2     3     6

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Amit', 'Sara', 'John', 'Priya', 'Ravi'],
    'Math': [80, 90, 75, 85, 60],
    'Science': [70, 95, 80, 75, 65],
    'Passed': [True, True, True, True, False]
})

In [63]:
df

    Name  Math  Science  Passed
0   Amit    80       70    True
1   Sara    90       95    True
2   John    75       80    True
3  Priya    85       75    True
4   Ravi    60       65   False

How many rows and columns are there?

In [64]:
df.shape

(5, 4)

What are the column names?

In [67]:
df.columns

Index(['Name', 'Math', 'Science', 'Passed'], dtype='object')

What is the data type of each column?

In [69]:
df.dtypes

Name       object
Math        int64
Science     int64
Passed       bool
dtype: object

How will you select only the Math marks column?

In [91]:
df['Math']

0    80
1    90
2    75
3    85
4    60
Name: Math, dtype: int64

How will you select Name and Science columns together?

In [102]:
df[['Name', 'Science']]

    Name  Science
0   Amit       70
1   Sara       95
2   John       80
3  Priya       75
4   Ravi       65

How will you get the first row?

In [97]:
df.iloc[0]

Name           Amit
Math             80
Science          70
Passed         True
Total           150
Average        75.0
Category    Average
Label           Yes
Name: 0, dtype: object

How will you get the last row?

In [98]:
df.iloc[-1]

Name           Ravi
Math             60
Science          65
Passed        False
Total           125
Average        62.5
Category    Average
Label            No
Name: 4, dtype: object

How will you get the 2nd row and 3rd column value?

In [106]:
print(df.iloc[1, 2])

95

How will you get first 3 rows?

In [107]:
print(df.iloc[0:3])

   Name  Math  Science  Passed  Total  Average   Category Label
0  Amit    80       70    True    150     75.0    Average   Yes
1  Sara    90       95    True    185     92.5  Excellent   Yes
2  John    75       80    True    155     77.5    Average   Yes

How will you get rows 2 to 4 and columns 1 to 2?

In [108]:
print(df.iloc[1:4, 0:2])

    Name  Math
1   Sara    90
2   John    75
3  Priya    85

How will you get all students who passed?

In [79]:
df[df['Passed'] == True]

    Name  Math  Science  Passed
0   Amit    80       70    True
1   Sara    90       95    True
2   John    75       80    True
3  Priya    85       75    True

How will you get students with Math > 80 AND Science > 80?

In [78]:
df[(df['Math']>80) & (df['Science']>80)]

   Name  Math  Science  Passed
1  Sara    90       95    True

How will you create a new column Total = Math + Science?

In [2]:
df['Total'] = df['Math'] + df['Science']
df

    Name  Math  Science  Passed  Total
0   Amit    80       70    True    150
1   Sara    90       95    True    185
2   John    75       80    True    155
3  Priya    85       75    True    160
4   Ravi    60       65   False    125

How will you create Average marks?

In [3]:
df['Average'] = df['Total']/2
df

    Name  Math  Science  Passed  Total  Average
0   Amit    80       70    True    150     75.0
1   Sara    90       95    True    185     92.5
2   John    75       80    True    155     77.5
3  Priya    85       75    True    160     80.0
4   Ravi    60       65   False    125     62.5

Above 80 → Excellent, else Average. Create new column called category

In [4]:
def remark(marks):
    if marks>80:
        return "Excellent"
    else:
        return "Average"
df["Category"] = df["Average"].apply(remark)
df

    Name  Math  Science  Passed  Total  Average   Category
0   Amit    80       70    True    150     75.0    Average
1   Sara    90       95    True    185     92.5  Excellent
2   John    75       80    True    155     77.5    Average
3  Priya    85       75    True    160     80.0    Average
4   Ravi    60       65   False    125     62.5    Average

How will you label Passed column:

True → "Yes", False → "No"

In [5]:
def grade(result):
    if result == True:
        return "Yes"
    else:
        return "No"
df['Label'] = df['Passed'].apply(grade)
df

    Name  Math  Science  Passed  Total  Average   Category Label
0   Amit    80       70    True    150     75.0    Average   Yes
1   Sara    90       95    True    185     92.5  Excellent   Yes
2   John    75       80    True    155     77.5    Average   Yes
3  Priya    85       75    True    160     80.0    Average   Yes
4   Ravi    60       65   False    125     62.5    Average    No

How will you rename column Math → Maths?

In [6]:
df.rename(columns = {'Math':'Maths'}, inplace = True)
df

    Name  Maths  Science  Passed  Total  Average   Category Label
0   Amit     80       70    True    150     75.0    Average   Yes
1   Sara     90       95    True    185     92.5  Excellent   Yes
2   John     75       80    True    155     77.5    Average   Yes
3  Priya     85       75    True    160     80.0    Average   Yes
4   Ravi     60       65   False    125     62.5    Average    No

How will you drop column Science?

In [8]:
df.drop(columns = ['Science'], inplace = True)
df

    Name  Maths  Passed  Total  Average   Category Label
0   Amit     80    True    150     75.0    Average   Yes
1   Sara     90    True    185     92.5  Excellent   Yes
2   John     75    True    155     77.5    Average   Yes
3  Priya     85    True    160     80.0    Average   Yes
4   Ravi     60   False    125     62.5    Average    No

What is the average Math score of class?

In [12]:
print(df['Maths'].mean())

78.0

How many students passed?

In [19]:
print(df['Passed'].sum())

4

read_csv

In [22]:
df5 = pd.read_csv(r"C:\Users\mishr\Python_Sessions\IPL2025Batters.csv")
df5.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37