# Pareto Analysis - 80/20 Rule

**80% Revenue from 20% Customers**

In [1]:
import pandas as pd

data = {
        'Customers': ['A', 'B', 'C' , 'D' , 'E'],
        'Monetary': [800, 1000, 200, 500, 100]
}

## Creating DataFrame

In [2]:
df = pd.DataFrame(data)

In [3]:
df.head()

  Customers  Monetary
0         A       800
1         B      1000
2         C       200
3         D       500
4         E       100

## Sorting Monetary in descending order

In [7]:
df = df.sort_values(by = 'Monetary', ascending=False)
df

  Customers  Monetary
1         B      1000
0         A       800
3         D       500
2         C       200
4         E       100

## Cumulative Revenue - adds all the revenue from start to a specific point

In [8]:
df['Cumulative_Revenue'] = df['Monetary'].cumsum()
df

  Customers  Monetary  Cumulative_Revenue
1         B      1000                1000
0         A       800                1800
3         D       500                2300
2         C       200                2500
4         E       100                2600

## Revenue Percentage

In [9]:
df['Revenue_Percent'] = df['Cumulative_Revenue']/df['Monetary'].sum() * 100
df

  Customers  Monetary  Cumulative_Revenue  Revenue_Percent
1         B      1000                1000        38.461538
0         A       800                1800        69.230769
3         D       500                2300        88.461538
2         C       200                2500        96.153846
4         E       100                2600       100.000000

## Resetting the index for proper sequence (important to calculate customer percentage)

In [10]:
df.reset_index(drop=True)

  Customers  Monetary  Cumulative_Revenue  Revenue_Percent
0         B      1000                1000        38.461538
1         A       800                1800        69.230769
2         D       500                2300        88.461538
3         C       200                2500        96.153846
4         E       100                2600       100.000000

## Customer percentage

In [12]:
df['Customer_Percent'] = (df.index+1)/len(df) * 100
df

  Customers  Monetary  Cumulative_Revenue  Revenue_Percent  Customer_Percent
1         B      1000                1000        38.461538              40.0
0         A       800                1800        69.230769              20.0
3         D       500                2300        88.461538              80.0
2         C       200                2500        96.153846              60.0
4         E       100                2600       100.000000             100.0

**This dataset does NOT satisfy the pareto analysis as 20% customers contribute only about 70% revenue.**